name: CD
on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/afifmakarim/repo/telegram-bot-test
            git pull origin master
            git status
            npm install --only-prod
            pm2 restart telebot
